In [1]:
import os
import pandas as pd

In [2]:
os.listdir()

['ARS.py',
 'SwabRegistrationForm_20211027_DRESORT.xlsx',
 'test.ipynb',
 'test.py']

In [3]:
df = pd.read_excel('SwabRegistrationForm_20211027_DRESORT.xlsx', skiprows=7)

In [4]:
df.shape

(23, 20)

In [5]:
df.columns

Index(['Registration Station *', 'Identification Number *',
       'Full Name (as in ID) ', 'Date of Birth (YYYYMMDD) ', 'Gender (M/F) *',
       'Nationality', 'Postal Code', 'Street Name', 'Level No', 'Unit No',
       'Time (24hr Format HH:mm) *', 'Contact No ', 'Disposition *', 'BatchId',
       'UTM No.', 'Status(S=Attended, R=Rejected) *',
       'Reason (Must include when Status is R, max character length is 255)',
       'Special Ops Notes (Max character length is 255)', 'ID Type *',
       'Country of Issue *'],
      dtype='object')

In [11]:
df = df.sort_values('Unit No')

In [14]:
df.columns

Index(['Registration Station *', 'Identification Number *',
       'Full Name (as in ID) ', 'Date of Birth (YYYYMMDD) ', 'Gender (M/F) *',
       'Nationality', 'Postal Code', 'Street Name', 'Level No', 'Unit No',
       'Time (24hr Format HH:mm) *', 'Contact No ', 'Disposition *', 'BatchId',
       'UTM No.', 'Status(S=Attended, R=Rejected) *',
       'Reason (Must include when Status is R, max character length is 255)',
       'Special Ops Notes (Max character length is 255)', 'ID Type *',
       'Country of Issue *'],
      dtype='object')

In [18]:
df['Identification Number *'].values.tolist()

['S1262237F',
 'G2041753L',
 'T0537061I',
 'S7918254J',
 'G6743955X',
 'S8136070G',
 'T0534389A',
 'S7620985E',
 'S9233939D',
 'T1402665C',
 'S8670719E',
 'S8372343B',
 'S9111114D',
 'T0107808E',
 'S8531291Z',
 'G8241042U',
 'G1646912U',
 'S8034939D',
 'S8818428I',
 'T0207155F',
 'S7021670A',
 'F2331271U',
 'S1745814J']

In [16]:
df

,Registration Station *,Identification Number *,Full Name (as in ID),Date of Birth (YYYYMMDD),Gender (M/F) *,Nationality,Postal Code,Street Name,Level No,Unit No,Time (24hr Format HH:mm) *,Contact No,Disposition *,BatchId,UTM No.,"Status(S=Attended, R=Rejected) *","Reason (Must include when Status is R, max character length is 255)",Special Ops Notes (Max character length is 255),ID Type *,Country of Issue *
15,NaN,S1262237F,LAI MOON KWAI,19570516,M,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,B122,NaN,83438436,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
11,NaN,G2041753L,TEE PEI CHAU,19870908,F,MALAYSIAN,519599,1 PASIR RIS CLOSE,NaN,B124,NaN,96439232,NaN,NaN,NaN,NaN,NaN,D6,FIN,SINGAPORE
4,NaN,T0537061I,NG YAO ZU RAPHEAL,20051224,M,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,B132,NaN,99999999,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
21,NaN,S7918254J,LING YOKE MEI FIONA -LIN YUWEI,19790625,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,B149,NaN,93888860,NaN,NaN,NaN,NaN,NaN,DISCORDANT ENTRY,NRIC,SINGAPORE
12,NaN,G6743955X,VENUGOPAL SATHEESH KUMAR,19840510,M,INDIAN,519599,1 PASIR RIS CLOSE,NaN,B354,NaN,93546013,NaN,NaN,NaN,NaN,NaN,D6,FIN,SINGAPORE
22,NaN,S8136070G,LEE POH CHIN,19811120,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M159,NaN,91165905,NaN,NaN,NaN,NaN,NaN,DISCORDANT ENTRY,NRIC,SINGAPORE
8,NaN,T0534389A,ONG EN QI SHERISE,20051128,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M163,NaN,99999999,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
2,NaN,S7620985E,TAN GEOK CHENG,19760719,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M163,NaN,97942659,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
10,NaN,S9233939D,CHUA MEI YAN,19920915,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M164,NaN,85113210,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
13,NaN,T1402665C,NURBELLA BINTE KHAMARUDDIN,20140131,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M167,NaN,99999999,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
14,NaN,S8670719E,YASMIN NACHIAR,19860506,F,INDIAN,519599,1 PASIR RIS CLOSE,NaN,M169,NaN,97120202,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
20,NaN,S8372343B,MOHAMED IQBAL NASRIN,19830526,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M173,NaN,99999999,NaN,NaN,NaN,NaN,NaN,DISCORDANT ENTRY,NRIC,SINGAPORE
18,NaN,S9111114D,NURULHUDA BINTE AMRAN,19910401,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M178,NaN,87427894,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
19,NaN,T0107808E,CHUA KAI TING JOELYN,20010311,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M179,NaN,83631482,NaN,NaN,NaN,NaN,NaN,DISCORDANT ENTRY,NRIC,SINGAPORE
17,NaN,S8531291Z,OOI KIAN HEONG (HUANG JIANXIONG),19850410,M,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M189,NaN,96727193,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
16,NaN,G8241042U,YU JUNCAI,19710819,M,CHINESE,519599,1 PASIR RIS CLOSE,NaN,M270,NaN,89372574,NaN,NaN,NaN,NaN,NaN,D6,FIN,SINGAPORE
5,NaN,G1646912U,SUCHETHA VINOD KUMAR,19780408,F,INDIAN,519599,1 PASIR RIS CLOSE,NaN,M368,NaN,86305318,NaN,NaN,NaN,NaN,NaN,D6,FIN,SINGAPORE
6,NaN,S8034939D,NEO TECK THENG CLEMENT,19801105,M,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M370,NaN,80117091,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
9,NaN,S8818428I,MUHAMMAD AHLAMI BIN SARDANI,19880525,M,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M371,NaN,88182376,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
7,NaN,T0207155F,AMANDA TAY XIU WEN,20020312,F,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M372,NaN,92429612,NaN,NaN,NaN,NaN,NaN,D6,NRIC,SINGAPORE
1,NaN,S7021670A,ABDUL RAZAK BIN SHAHBUDDIN,19700702,M,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M374,NaN,90106830,NaN,NaN,NaN,NaN,NaN,D10,NRIC,SINGAPORE
3,NaN,F2331271U,HUANG JUNFA,19651112,M,CHINESE,519599,1 PASIR RIS CLOSE,NaN,M385,NaN,82803199,NaN,NaN,NaN,NaN,NaN,D6,FIN,SINGAPORE
0,NaN,S1745814J,TAY PUAY CHWAN,19660919,M,SINGAPOREAN,519599,1 PASIR RIS CLOSE,NaN,M387,NaN,97964724,NaN,NaN,NaN,NaN,NaN,D10,NRIC,SINGAPORE